"""add team verdicts table

Revision ID: 2f12598860c0
Revises: 531e6d47a893
Create Date: 2026-08-17 14:45:26.621876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f12598860c0'
down_revision: Union[str, Sequence[str], None] = '531e6d47a893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_verdicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('verdict', sa.String(length=8), nullable=False),
    sa.Column('key_factors', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('price_at_call', sa.Float(), nullable=False),
    sa.Column('call_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker', 'call_date', name='uq_team_verdict_per_ticker_day')
    )
    op.create_index(op.f('ix_team_verdicts_call_date'), 'team_verdicts', ['call_date'], unique=False)
    op.create_index(op.f('ix_team_verdicts_ticker'), 'team_verdicts', ['ticker'], unique=False)
    op.create_index(op.f('ix_team_verdicts_user_id'), 'team_verdicts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_verdicts_user_id'), table_name='team_verdicts')
    op.drop_index(op.f('ix_team_verdicts_ticker'), table_name='team_verdicts')
    op.drop_index(op.f('ix_team_verdicts_call_date'), table_name='team_verdicts')
    op.drop_table('team_verdicts')
    # ### end Alembic commands ###
