"""add brokerage domain to connections

Revision ID: 30b76b3a3833
Revises: 088b7eb8dc60
Create Date: 2026-08-13 18:59:24.591087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30b76b3a3833'
down_revision: Union[str, Sequence[str], None] = '088b7eb8dc60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brokerage_connections', sa.Column('brokerage_domain', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brokerage_connections', 'brokerage_domain')
    # ### end Alembic commands ###
