"""add brokerage connections and accounts

Revision ID: 35630efb3ede
Revises: 8843a9767e00
Create Date: 2026-08-13 16:12:13.505511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35630efb3ede'
down_revision: Union[str, Sequence[str], None] = '8843a9767e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokerage_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snaptrade_connection_id', sa.String(length=64), nullable=True),
    sa.Column('portal_session_id', sa.String(length=64), nullable=True),
    sa.Column('brokerage_name', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snaptrade_connection_id')
    )
    op.create_index(op.f('ix_brokerage_connections_user_id'), 'brokerage_connections', ['user_id'], unique=False)
    op.create_table('brokerage_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('snaptrade_account_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('number_last4', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['brokerage_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snaptrade_account_id')
    )
    op.create_index(op.f('ix_brokerage_accounts_connection_id'), 'brokerage_accounts', ['connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brokerage_accounts_connection_id'), table_name='brokerage_accounts')
    op.drop_table('brokerage_accounts')
    op.drop_index(op.f('ix_brokerage_connections_user_id'), table_name='brokerage_connections')
    op.drop_table('brokerage_connections')
    # ### end Alembic commands ###
