"""add theme portfolios tables

Revision ID: 3f0a55b8f7db
Revises: d3e1f5153bec
Create Date: 2026-08-31 14:54:32.239637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f0a55b8f7db'
down_revision: Union[str, Sequence[str], None] = 'd3e1f5153bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme_portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme_key', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theme_portfolios_created_at'), 'theme_portfolios', ['created_at'], unique=False)
    op.create_index(op.f('ix_theme_portfolios_theme_key'), 'theme_portfolios', ['theme_key'], unique=False)
    op.create_index(op.f('ix_theme_portfolios_user_id'), 'theme_portfolios', ['user_id'], unique=False)
    op.create_table('theme_portfolio_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme_portfolio_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('verdict', sa.String(length=8), nullable=False),
    sa.Column('weight_percent', sa.Float(), nullable=False),
    sa.Column('dollar_amount', sa.Float(), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['theme_portfolio_id'], ['theme_portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theme_portfolio_picks_theme_portfolio_id'), 'theme_portfolio_picks', ['theme_portfolio_id'], unique=False)
    op.create_index(op.f('ix_theme_portfolio_picks_ticker'), 'theme_portfolio_picks', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_theme_portfolio_picks_ticker'), table_name='theme_portfolio_picks')
    op.drop_index(op.f('ix_theme_portfolio_picks_theme_portfolio_id'), table_name='theme_portfolio_picks')
    op.drop_table('theme_portfolio_picks')
    op.drop_index(op.f('ix_theme_portfolios_user_id'), table_name='theme_portfolios')
    op.drop_index(op.f('ix_theme_portfolios_theme_key'), table_name='theme_portfolios')
    op.drop_index(op.f('ix_theme_portfolios_created_at'), table_name='theme_portfolios')
    op.drop_table('theme_portfolios')
    # ### end Alembic commands ###
