"""add retired_at to theme_suggestions

Revision ID: 66d7508af32c
Revises: 8751c54bca97
Create Date: 2026-09-01 14:16:05.347830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66d7508af32c'
down_revision: Union[str, Sequence[str], None] = '8751c54bca97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theme_suggestions', sa.Column('retired_at', sa.DateTime(), nullable=True))
    with op.batch_alter_table('theme_suggestions') as batch_op:
        batch_op.drop_constraint(op.f('uq_theme_suggestion_theme_status'), type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme_suggestions') as batch_op:
        batch_op.create_unique_constraint(op.f('uq_theme_suggestion_theme_status'), ['theme_key', 'status'])
    op.drop_column('theme_suggestions', 'retired_at')
    # ### end Alembic commands ###
