"""add theme_suggestions tables

Revision ID: 8751c54bca97
Revises: d15a3e399251
Create Date: 2026-09-01 13:11:56.433408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8751c54bca97'
down_revision: Union[str, Sequence[str], None] = 'd15a3e399251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme_key', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theme_key', 'status', name='uq_theme_suggestion_theme_status')
    )
    op.create_index(op.f('ix_theme_suggestions_theme_key'), 'theme_suggestions', ['theme_key'], unique=False)
    op.create_table('theme_suggestion_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme_suggestion_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('weight_percent', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('price_at_buy', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['theme_suggestion_id'], ['theme_suggestions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theme_suggestion_picks_theme_suggestion_id'), 'theme_suggestion_picks', ['theme_suggestion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_theme_suggestion_picks_theme_suggestion_id'), table_name='theme_suggestion_picks')
    op.drop_table('theme_suggestion_picks')
    op.drop_index(op.f('ix_theme_suggestions_theme_key'), table_name='theme_suggestions')
    op.drop_table('theme_suggestions')
    # ### end Alembic commands ###
