"""add theme_filings_picks table

Revision ID: 9bead76d7648
Revises: 00cee284d001
Create Date: 2026-09-01 12:22:58.717384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bead76d7648'
down_revision: Union[str, Sequence[str], None] = '00cee284d001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme_filings_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme_key', sa.String(length=32), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theme_filings_picks_generated_at'), 'theme_filings_picks', ['generated_at'], unique=False)
    op.create_index(op.f('ix_theme_filings_picks_theme_key'), 'theme_filings_picks', ['theme_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_theme_filings_picks_theme_key'), table_name='theme_filings_picks')
    op.drop_index(op.f('ix_theme_filings_picks_generated_at'), table_name='theme_filings_picks')
    op.drop_table('theme_filings_picks')
    # ### end Alembic commands ###
