"""add predicted price and horizon to team verdicts

Revision ID: bad2bd15f75f
Revises: 2f12598860c0
Create Date: 2026-08-17 16:20:51.528556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad2bd15f75f'
down_revision: Union[str, Sequence[str], None] = '2f12598860c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_verdicts', sa.Column('predicted_price', sa.Float(), nullable=True))
    op.add_column('team_verdicts', sa.Column('predicted_horizon', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_verdicts', 'predicted_horizon')
    op.drop_column('team_verdicts', 'predicted_price')
    # ### end Alembic commands ###
