"""add pipeline audit trail to theme_filings_picks

Revision ID: d15a3e399251
Revises: 9bead76d7648
Create Date: 2026-09-01 12:37:49.209087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd15a3e399251'
down_revision: Union[str, Sequence[str], None] = '9bead76d7648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theme_filings_picks', sa.Column('status', sa.String(length=20), nullable=False, server_default='kept'))
    op.add_column('theme_filings_picks', sa.Column('hit_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('theme_filings_picks', sa.Column('matched_keywords', sa.Text(), nullable=False, server_default=''))
    op.add_column('theme_filings_picks', sa.Column('market_cap', sa.Float(), nullable=True))
    with op.batch_alter_table('theme_filings_picks') as batch_op:
        batch_op.alter_column('relevance_score', existing_type=sa.FLOAT(), nullable=True)
        batch_op.alter_column('rationale', existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme_filings_picks') as batch_op:
        batch_op.alter_column('rationale', existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column('relevance_score', existing_type=sa.FLOAT(), nullable=False)
    op.drop_column('theme_filings_picks', 'market_cap')
    op.drop_column('theme_filings_picks', 'matched_keywords')
    op.drop_column('theme_filings_picks', 'hit_count')
    op.drop_column('theme_filings_picks', 'status')
    # ### end Alembic commands ###
