"""add specialist calls table

Revision ID: d3e1f5153bec
Revises: bad2bd15f75f
Create Date: 2026-08-28 12:24:24.531065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e1f5153bec'
down_revision: Union[str, Sequence[str], None] = 'bad2bd15f75f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialist_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_verdict_id', sa.Integer(), nullable=False),
    sa.Column('specialist_key', sa.String(length=32), nullable=False),
    sa.Column('signal', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_verdict_id'], ['team_verdicts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialist_calls_specialist_key'), 'specialist_calls', ['specialist_key'], unique=False)
    op.create_index(op.f('ix_specialist_calls_team_verdict_id'), 'specialist_calls', ['team_verdict_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_specialist_calls_team_verdict_id'), table_name='specialist_calls')
    op.drop_index(op.f('ix_specialist_calls_specialist_key'), table_name='specialist_calls')
    op.drop_table('specialist_calls')
    # ### end Alembic commands ###
